# Generated by Django 3.0.2 on 2020-03-07 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('shortDescription', models.CharField(max_length=160)),
                ('days', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('currency', models.CharField(choices=[('$', '$')], default='$', max_length=1)),
                ('locationKeywords', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LocationBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lbCity', models.CharField(max_length=50)),
                ('lbDays', models.IntegerField()),
                ('lbCurrency', models.CharField(choices=[('$', '$')], default='$', max_length=1)),
                ('lbForeignKey', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='RuckSackApp.Itinerary')),
            ],
        ),
    ]
